version: '2'
services:
  web:
    build: ./webapp
    command: npm run dev
    volumes:
      - ./webapp:/opt/earthsci/src/app
      - /opt/earthsci/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./sendgrid.env
  server:
    build: ./server
    command: npm run start
    depends_on:
      - mariadb
    expose:
      - 8000
    environment:
      MYSQL_HOST: mariadb
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    links:
      - mariadb
  mariadb:
    image: mariadb:10.5.1-bionic
    volumes:
      - ./scripts/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql-root-pass'
      MYSQL_USER: 'science'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'earth_sci'
