version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./webapp:/opt/earthsci/src/app
      - /opt/earthsci/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5.1-bionic
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql-root-pass'
      MYSQL_USER: 'science'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'earth_sci'
      SENDGRID_API_KEY: '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'
