version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./webapp:/opt/earthsci/webapp
      - /opt/earthsci/webapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://science@postgres/earth_sci
  postgres:
    image: postgres:12.2
    ports:
      - "127.0.0.1:8080:5432"
    environment:
      POSTGRES_USER: science
      POSTGRES_DB: earth_sci
      POSTGRES_HOST_AUTH_METHOD: trust
